version: '3.7'
services:
  redis:
    image: redis
    container_name: sampleboard_redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - backend

  postgres:
    container_name: sampleboard_postgresql
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "kim"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "sampleboard"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend



volumes:
  postgres_data:
    name: sampleboard_postgres_data

networks:
  backend:
    name: backend
    driver: bridge